Remove Non-Latin-Characters Apps Test
I only added it originally out of a surplus of thoroughness, but the
fancy characters are causing weird failures in the DTT:

    FAILED TESTS:
      unit tests
	SubmissionStatusAssessmentsTable
	  âœ– renders localized submission timestamps
	    HeadlessChrome 0.0.0 (Linux 0.0.0)
	  AssertionError: expected 'Ù¢Ù§â€/Ù¡â€/Ù¡Ù¤Ù¤Ù  Ù‡Ù€ Ù¨:Ù¥Ù¢:Ù Ù¥ Ù…' to equal 'Ù¢Ù§â€/Ù¡â€/Ù¡Ù¤Ù¤Ù  Ù‡Ù€ ÙÙŠ Ù¨:Ù¥Ù¢:Ù Ù¥ Ù…'

	  + expected - actual

	  -Ù¢Ù§â€/Ù¡â€/Ù¡Ù¤Ù¤Ù  Ù‡Ù€ Ù¨:Ù¥Ù¢:Ù Ù¥ Ù…
	  +Ù¢Ù§â€/Ù¡â€/Ù¡Ù¤Ù¤Ù  Ù‡Ù€ ÙÙŠ Ù¨:Ù¥Ù¢:Ù Ù¥ Ù…