Update `rake` Gem
Specifically to pick up https://github.com/ruby/rake/pull/211, which is required for Rails 6.1 support; without it, we get `undefined method ``with_application' for Rake:Module (NoMethodError)` when trying to run any rails script.

Specifically, I implemented this by running `bundle update rake scss_lint`, to also pick up the `scss_lint` change "Relax gem dependency constraints to allow rake 12.x"

- https://github.com/sds/scss-lint/blob/master/CHANGELOG.md#0510
- https://github.com/ruby/rake/releases/tag/v12.2.0

Tested locally that this resolves for me the problems with running rake tasks on Rails 6.1

Relying on existing tests to verify that this does not otherwise result in any change to functionality.