Default `params` to empty hash in test helper
This is required for the 5.1 upgrade. I'm still not entirely sure what changed to make this necessary, but for some reason in 5.1 we started getting a bunch of errors like:

```
===[0m[1000D[KERROR["test_facilitator_calling_get_index_should_receive_forbidden_to_", "RegionalPartnersControllerTest", 677.4297561550002]
 test_facilitator_calling_get_index_should_receive_forbidden_to_#RegionalPartnersControllerTest (677.43s)
NoMethodError:         NoMethodError: undefined method `symbolize_keys' for nil:NilClass
            test/test_helper.rb:477:in `block (2 levels) in test_user_gets_response_for'
            test/testing/capture_queries.rb:27:in `assert_queries'
            test/test_helper.rb:476:in `block in test_user_gets_response_for'
            test/testing/setup_all_and_teardown_all.rb:36:in `run'
```

It seems like we're passing `params` as `nil` in a couple of places, and although that worked in Rails 5.0, 5.1 is having none of it.

The simple solution is to make sure we're defaulting params to an empty hash.