Add Unit Test for DynamicConfig Controller
Follow-up to https://github.com/code-dot-org/code-dot-org/pull/54601, which broke the web interface for interacting with Gatekeeper, and to https://github.com/code-dot-org/code-dot-org/pull/55124, which fixed it.

This PR adds unit tests for this controller. If these tests had been around prior to the fixes being added, they would have failed with the following errors:

```
ERROR["test_accessible_by_admins", "DynamicConfigControllerTest", 7.780938796990085]
 test_accessible_by_admins#DynamicConfigControllerTest (7.78s)
Minitest::UnexpectedError:         NoMethodError: undefined method `update_cache' for #<DatastoreCache:0x000055d9aa438008 @datastore=#<MemoryAdapter:0x000055d9aa4381e8 @hash={}>, @identifier="gatekeeper_test", @local_cache={}, @local_cache_expiration=5, @local_cache_last_refreshed_at=2023-11-22 22:58:35.803446947 +0000>
        Did you mean?  update_local_cache
            app/controllers/dynamic_config_controller.rb:18:in `gatekeeper_show'
            app/controllers/application_controller.rb:181:in `block in with_locale'
            app/controllers/application_controller.rb:180:in `with_locale'
            test/controllers/dynamic_config_controller_test.rb:22:in `block in <class:DynamicConfigControllerTest>'
            test/testing/setup_all_and_teardown_all.rb:36:in `run'

ERROR["test_can_delete_gatekeeper_values", "DynamicConfigControllerTest", 7.828119493991835]
 test_can_delete_gatekeeper_values#DynamicConfigControllerTest (7.83s)
Minitest::UnexpectedError:         NoMethodError: undefined method `update_cache' for #<DatastoreCache:0x000055d9aa438008 @datastore=#<MemoryAdapter:0x000055d9aa4381e8 @hash={"test delete"=>"{\"[[\\\"foo\\\",\\\"bar\\\"]]\":true}"}>, @identifier="gatekeeper_test", @local_cache={"test delete"=>{"[[\"foo\",\"bar\"]]"=>true}}, @local_cache_expiration=5, @local_cache_last_refreshed_at=2023-11-22 23:01:47.921592239 +0000>
        Did you mean?  update_local_cache
            app/controllers/dynamic_config_controller.rb:29:in `gatekeeper_delete'
            app/controllers/application_controller.rb:181:in `block in with_locale'
            app/controllers/application_controller.rb:180:in `with_locale'
            test/controllers/dynamic_config_controller_test.rb:53:in `block in <class:DynamicConfigControllerTest>'
            test/testing/setup_all_and_teardown_all.rb:36:in `run'

ERROR["test_can_update_gatekeeper_values", "DynamicConfigControllerTest", 7.907844690984348]
 test_can_update_gatekeeper_values#DynamicConfigControllerTest (7.91s)
Minitest::UnexpectedError:         NoMethodError: undefined method `update_cache' for #<DatastoreCache:0x000055d9aa438008 @datastore=#<MemoryAdapter:0x000055d9aa4381e8 @hash={}>, @identifier="gatekeeper_test", @local_cache={}, @local_cache_expiration=5, @local_cache_last_refreshed_at=2023-11-22 23:01:47.973313911 +0000>
        Did you mean?  update_local_cache
            app/controllers/dynamic_config_controller.rb:43:in `gatekeeper_set'
            app/controllers/application_controller.rb:181:in `block in with_locale'
            app/controllers/application_controller.rb:180:in `with_locale'
            test/controllers/dynamic_config_controller_test.rb:44:in `block in <class:DynamicConfigControllerTest>'
            test/testing/setup_all_and_teardown_all.rb:36:in `run'
```

With the fixes in place, the tests now all pass.