Run SauceLabs tests on CircleCI (#8503)
* Test running Circle test against Sauce Labs

* Update test

* Try adding colons

* Try indentation change

* Make map params a map

* - Decrypt levels
- Add sauce labs to locals.yml

* Try using full build

* Run all tests.
- Remove extra seeds/setup

* Skip default database seeding

* Try to force skipping database step

* Update runner to auto-retry

* Try 10 parallel tests

* Try not double-running grunt tests, even fewer parallel test instances

* Set circle tests to "green" mode. Should fix hourOfCode_signedIn.feature—(fixing it from logging out on visits to /hoc/1)

* Try 7 parallel instances (will check for out of memory error)

* Try 6 parallel instances

* Try removing require from steps

* Update circle.yml to copy over artifacts. Remove some gems from Gemfile based on bundle_require branch

* Remove moreutils and `ts` (moreutils conflicting with parallel used by CircleCI)

* Add blank? require

* Add time

* Require environment for i18n translate
- Require konacha in Gemfile again
- Include ActiveSupport keygenerator in cookie helpers

* Increase # parallel

* Try 13 parallel tests

* Try 10 parallel

* Try 9 tests

* Try 8 parallel

* Undo gemfile changes

* Move require rails env out into own helper

* Parallelize across containers

* Try running parallel failure in non-parallel

* Try removing single quotes

* Test adding [run-ui] annotation to run tests

* Check for `sudo npm` on Linux [run-ui]
- Fix alias yaml syntax

* Fix node reference (might be circular now?)

* Use `which node` for symlink

* Undo node changes, use npm_use_sudo: false

* Update to do initial database setup

* Build code studio, explicitly run apps tests using npm test

* Update instance node version

* Try building only if files changed (may skip many tests). [run-ui-tests]

* Use script for [run-ui-tests]

* Fix location

* Add new cache location [run-ui-tests]

* Move UI test skipping logic into Rakefile :circle namespace [ui test]

* New test rake tasks [test all] [test ui]

* Add system background helper, fix ./bin/sc command

* Fix rake param name [test ui] [test all]

* Try using system_with_hipchat_logging to get output on success

* Bump file [test ui] [test all]

* Fix indentation
- Collapse single settings
- Add longer timeout for long-running tests scripts with little output

* Bump for test run [test ui] [test all]

* Attempt to fix circle.yml formatting

* Attempt to fix circle.yml formatting #2 [test ui] [test all]

* Try using new system commands

* Bump for test [test ui]

* Fix timeout usage of rails helpers

* Use magic-retry for test rerun [test ui]

* Bump to test everything [test all]

* Move setup steps into dependencies phase so caching occurs.

* Fix up system command to not print 2>&1 for quiet commands

* Force development dependency installation [test ui]

* Try using --with [test ui]

* Try using --without '' [test ui]

* Try using 4 parallel [test ui]

* Try removing development exclusion after rake install

* Try also bundle installing after bundle config removal

* Move bundle install to end [test ui]

* Only use rerun when development [test all] [test ui]

* Try removing  ./bin/dashboard-server (already auto-running?) [test all] [test ui]
- Remove redundant DB steps

* Move set_hoc_flags to after DB setup [test all] [test ui]

* Move hoc flag comment

* Add back dashboard server [test ui]

* Try without set_hoc_flags [test all] [test ui]

* Set hoc flags to green (don't require login for star wars et al) [test all] [test ui]

* Try adding script.id log [test all]

* More debug calls [test all]

* Try running dashboard with rails/rack env set [test ui]

* Try flipping order [grab scripts on test time] [test all] [test ui]

* Try seeding between unit tests and UI tests [test all] [test ui]

* Fix typo [test ui] [test all]

* Localize apps. Retry 4 times. [test ui] [test all]

* Fix script test. Add explanation to re-seeding. [test all] [test ui]

* Remove assets/sources s3 directory overrides [test all] [test ui]

* Add @no_circle annotation. Run without @no_circle tests when running UI tests via Circle [test ui] [test all]

* Extract circle.rake, test.rake. Move git utilities into GitUtils.
- Determine base branch through a mapping

* Fix spacing , force test run. [test ui] [test all]

* Reflect moved method

* Force test [test all] [test ui]

* Update grunt-sass to potentially fix circleci failure

Potential fix for issue: `Error: The `libsass` binding was not found in [CDO]/apps/node_modules/grunt-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node`

* Bump file with whitespace change to force circle test [test ui] [test all]

* Introduce whitespace change to trigger build [test all] [test ui]

* 16 tests in parallel [test ui]

* Skip tests with circle issues [test ui]

* Try 30 parallel [test ui]

* Try 20 parallel [test ui]

* Try 40 in parallel [test all] [test ui]

* Update to stream output. Try 30 parallel. [test ui] [test all]

* Test adding hipchat logging for failures [test ui] [test all]

* Include format_duration (dupication) temporarily [test ui] [test all]

* Pull out multiple definitions of `format_duration` to `RakeUtils.format_duration` [test all] [test ui]

* Pull *stream_output commands into RakeUtils (aliasing the original "system" command). [test all] [test ui]

* Merge remote-tracking branch 'origin/staging' into sauce-circle-fast [test all] [test ui]

* Try different logging, see if shows up in circleci output [test all] [test ui]

* Properly use original system [test all] [test ui]

* Use correct way of aliasing methods [test all] [test ui]

* Fix streaming command exit status output [test all] [test ui]

* Try magic retry [test all] [test ui]

* Back to retry count (memory usage effect?) [test all] [test ui]

* Try with 35 parallel [test all] [test ui]

* Remove test logging, remove duplicate "Running " from strings [test all] [test ui]

* Move tag definitions out of circle.yml parameters and into circle.rake as constants [test ui] [test all]

* Add explanation of rake utils system command aliasing.

* Remove unused helper file [test all] [test ui]

* Try latest sauce connect [test ui]

* Try latest sauce connect (correct unzip) [test ui]

* Try adding no_circle to free response submittable [test ui]

* Update documentation [test ui] [test all]

* Add ? to fnmatch. [test all]

* Use Kernel.system rather than aliasing. $?.exitstatus -> $?.success? [test all]

* Include apps in code-studio testing dependencies

* Undo unintentional change from merge

* Change diff detection glob behavior. Add git utils test.

* Move glob_matches_file_path? into rake_utils

* Fix reference. Add lib/* to shared test triggers.

* Fix changed PR file detection method.

* Make changed file output a bit easier to scan.

* Try using origin/