Ruby 3.3.4: pre-upgrade everything that can apply to Ruby 3.0.5 too (#60546)
* Gemfile.lock: `bundle update cld`, cld => 0.13.0
* Gemfile.lock: `bundle update css_parser`, File.exists? no longer exists
* yaml.rb: YAML.load only takes one arg with psych
* Gemfile: eyes_selenium => 6.3.7 + `bundle update eyes_selenium` updates selenium-webdriver to 4.10.0
* bin/dashboard-server loads studio
* remove our custom fork of sprockets (backport of rails 4=>3, outdated anyway) which was spewing warnings to console
* pycall => 1.5.2
* ChatClient: print messages in dev too
* Remove workaround from Gemfile marked 'This is a temporary workaround - remove when bundler version is >=2.0'
* Gemfile.lock: bundle => 2.5.17
* Remove unnecessary (?) `gem install bundler` step from SETUP.md
* Redo rake => 13.2.1 upgrade in /Gemfile
* honeybadger.yml: ensure API key is a string not an int, dev values of "000000" were turning into the int 0 which confuses the poor badger
* Fix pre-Ruby-3.4 warnings: "___ was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0"
* Gemfile: redcarpet =>3.6.0 to fix a warning, see: https://www.redmine.org/issues/38118
* `bundle update docker-api excon` to fix `kitchen create` for dokken driver
* cloud_formation.rb: add Date to YAML.load permitted_classes to fix `rake adhoc:start`
* Gemfile: highline => 3.1.0, fixes warnings on `rake adhoc:start`, see: https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282228816
* Gemfile.lock: `bundle update honeybadger`, speculative fix to https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282188277
* Gemfile: add explicit `syslog` to fix Ruby 3.4 deprecation warnings
* profanity_privacy_helper: disable for Java Lab etc, see: https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282270302
* Revert "Gemfile.lock: `bundle update honeybadger`, speculative fix to https://github.com/code-dot-org/code-dot-org/pull/60329#issuecomment-2282188277"
* Check the honeybadger backend as the test runs
* Gemfile.lock: `bundle update rubocop`
* honeybadger_test: assert_equal 'test', config.backend
* honeybadger_test: print extensive debug spew
* honeybadger_test: search notices for one from honeybadger_error controller
* generateSharedConstants.rb: `require 'ostruct'`
* .rubocop_[todo|new].yml: update for rubocop 1.65
* honeybadger_test: cast notice to json before using
* Gemfile.lock: `bundle update vcr`
* fake_dashboard.rb: fix Psych::AliasesNotEnabled: Alias parsing was not enabled.
* pegasus/honeybadger.yml: fix NoMethodError: undefined method `=~' for an instance of Integer
* pegasus page.haml: fix undefined method `exists?' for class File
* Gemfile: image_optim apply ruby 3.1 backport to our custom fork
* Gemfile: fix elijah review suggestions, move Ruby 3.4 deprecation gems to top
* honeybadger_test: fix elijah review suggestions, comment changes to test
* Gemfile: switch image_optim back to cdo branch
* Revert "ChatClient: print messages in dev too"
* cookbooks/Gemfile and Gemfile.lock: reduce diff with ruby-3.3
* cdo-ruby/.kitchen.yml: use ubuntu-20.04
* cdo-ruby/.kitchen.yml: enable serverspec verifier (currently was disabled = no verification)
cdo-ruby/ ruby_spec.rb: verify versions
* cdo-ruby ruby-build: switch from serverspec to inspec which we generally use
* ruby_spec.rb: convert from serverspec to inspec
* cookbooks/cdo-ruby ruby_spec.rb: switch back to verifying ruby 3.0.5 versions
* cloud_formation.rb: work on ruby 3.0.5 AND 3.3.4
* [test eyes]