Don't enable `utc_to_local_returns_utc_offset_times` just yet
We're not ready for it:

    [2023-01-19 01:09:02] RAILS_ENV=test RACK_ENV=test bundle exec rake db:create db:test:prepare
    rake aborted!
    NoMethodError: undefined method `utc_to_local_returns_utc_offset_times=' for ActiveSupport:Module
    /drone/src/dashboard/config/initializers/new_framework_defaults_6_1.rb:36:in `<top (required)>'
    /drone/src/dashboard/config/environment.rb:13:in `<top (required)>'
    /home/circleci/.rbenv/versions/2.7.5/bin/bundle:23:in `load'
    /home/circleci/.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'
    Tasks: TOP => db:create => db:load_config => environment
    (See full trace by running task with --trace)
    rake aborted!
    'RAILS_ENV=test RACK_ENV=test bundle exec rake db:create db:test:prepare' returned 1