Abandon staging build after committing updated schema_cache.dump file
The last several times staging has committed an update to the `schema_cache.dump` file, the build has subsequently failed when the machine is unable to push the new commit because new work has been merged to the remote.

```
RAILS_ENV=staging RACK_ENV=staging bundle exec rake db:schema:cache:dump
git add /home/ubuntu/staging/dashboard/db/schema_cache.dump
git commit -m "Update schema cache dump after schema changes." /home/ubuntu/staging/dashboard/db/schema_cache.dump
git push origin staging
rake aborted!
'git push origin staging' returned 1
To github.com:code-dot-org/code-dot-org.git
 ! [rejected]        staging -> staging (fetch first)
error: failed to push some refs to 'git@github.com:code-dot-org/code-dot-org.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Then, in addition to _that_ build failing, subsequent builds also fail to start because the local machine is ahead (with the unpushed commit) and builds will continue to fail until someone ssh's in and runs `git pull && git push`.

Here, I propose that we let staging proactively `git pull --ff-only origin staging` right before committing the updated schema_cache.dump to increase the odds that it will be able to successfully push the new commit.

Because pulling new changes may invalidate the current build, immediately after pushing the new commit we abandon the build (with a more useful message) so that the next build can start without developer intervention.